### ISSUE TITLE
Add EULA page

### ISSUE THREAD

**Issue by sidnny** [angelshot/angelshot.ltd#10]
Need to add a `/eula` endpoint to the site for https://github.com/angelshot/AngelBot/issues/38.

[Copy deck](https://docs.google.com/document/d/1ZNuXmOtlDjF9DlrHmcZnJo1u54D8fgj5GIuVkQAXiNc/edit#heading=h.idj6wrhh9mx4)

**Comment by magreen521** [comment]
Submitted pull request: https://github.com/angelshot/angelshot.ltd/pull/66
