### ISSUE TITLE
Add citations to stats

### ISSUE THREAD

**Issue by sidnny** [angelshot/angelshot.ltd#39]
Add attribution to stats taken from:
- [x] https://www.rainn.org/statistics
- [x] https://www.cdc.gov/violenceprevention/sexualviolence/index.html
- [x] https://www.youthpower.org/youthpower-issues/topics/non-consensual-sex

**Comment by magreen521** [comment]
**Website content:** "According to the CDC, 1 in 3 women and 1 in 4 men experienced sexual violence involving physical contact during their lifetimes."
**Source:** https://www.cdc.gov/violenceprevention/sexualviolence/fastfact.html

**Website content:** "More than half of sexual assault incidents occurs while the victim is pursuing leisure activities away from home, and instances of rape within colleges are severely under-reported."
**Source:** https://www.bjs.gov/index.cfm?ty=pbdetail&iid=5176

**Website content:** "51% of student rape and sexual assault victimizations occurred while the victim was pursuing leisure activities away from home."
**Source**: https://www.bjs.gov/index.cfm?ty=pbdetail&iid=5176

**Website content:** "College women are twice as likely to be sexually assaulted than robbed."
**Source:** https://www.rainn.org/statistics/campus-sexual-violence

**Website content:** "80% of rape and sexual assault victimizations of students and 67% of non-students go unreported to police."
**Source:** https://www.bjs.gov/index.cfm?ty=pbdetail&iid=5176

**Website content:** "Fewer than 1 in 5 female victims received assistance from a victim services agency."
**Source:** https://www.bjs.gov/content/pub/pdf/rsavcaf9513.pdf

**Website content:** In about 80% of rape and sexual assault victimizations, the offender was known to the victim.
**Source:** https://www.bjs.gov/index.cfm?ty=pbdetail&iid=5176

**Website content:** "About a quarter of victims who did not report to police believed the incident was a personal matter, and 1 in 5 stated a fear of reprisal."
**Sources:**
https://www.bjs.gov/content/pub/pdf/rsavcaf9513.pdf
https://www.rainn.org/statistics/campus-sexual-violence

**Comment by magreen521** [comment]
Citations in MLA format:
1. **Source:** https://www.cdc.gov/violenceprevention/sexualviolence/fastfact.html
**Citation:** "Preventing Sexual Violence." _Centers for Disease Control and Prevention_, 17 January 2020, https://www.cdc.gov/violenceprevention/sexualviolence/fastfact.html.
2. **Sources:** https://www.bjs.gov/index.cfm?ty=pbdetail&iid=5176, https://www.bjs.gov/content/pub/pdf/rsavcaf9513.pdf
**Citation:** Sinozich, Sofi and Lynn Langton, Ph.D. “Rape And Sexual Assault Among College-Age Females, 1995-2013.” _Bureau of Justice Statistics_, 11 December 2014, https://www.bjs.gov/index.cfm?ty=pbdetail&iid=5176.
3. **Source:** https://www.rainn.org/statistics/campus-sexual-violence
**Citation:** “Campus Sexual Violence: Statistics.” _Rape, Abuse, & Incest National Network_, 2020, https://www.rainn.org/statistics/campus-sexual-violence.

MLA guidelines:
https://owl.purdue.edu/owl/research_and_citation/mla_style/mla_formatting_and_style_guide/mla_works_cited_electronic_sources.html
https://owl.purdue.edu/owl/research_and_citation/mla_style/mla_formatting_and_style_guide/mla_in_text_citations_the_basics.html

**Comment by magreen521** [comment]
Didn't trace any of the stats to https://www.youthpower.org/youthpower-issues/topics/non-consensual-sex

**Comment by magreen521** [comment]
Submitted pull request: https://github.com/angelshot/angelshot.ltd/pull/69
