### ISSUE TITLE
Add conversion tracking (global)

### ISSUE THREAD

**Issue by nub4life** [angelshot/angelshot.ltd#67]
In order to support and track our ad campaigns, we have to add some code snippets to our pages.

Add this in between the `head` tags:
`<!-- Global site tag (gtag.js) - Google Ads: 605133217 --> <script async src="https://www.googletagmanager.com/gtag/js?id=AW-605133217"></script> <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'AW-605133217'); </script>`

**Comment by magreen521** [comment]
Submitted pull request: https://github.com/angelshot/angelshot.ltd/pull/70
